[project]
name = "tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "djangorestframework>=3.16.0",
    "pygments>=2.19.2",
]

[dependency-groups]
dev = [
    "httpie>=3.2.4",
    "ruff>=0.12.3",
]
